config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :employees
  #public pages routes/custom pages 
  get "about"=>'pages#about_us'
  get "contact"=>'pages#contact_us'
  get "privacy-policy"=>'pages#privacy_policy'
  get "terms-and-conditions"=>'pages#terms_and_conditions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :documents
    
    validates :first_name, :last_name, presence: true
    validates :personal_email, presence: true, uniqueness: true
    validates :city, :state, :country, :pindcode, :address_line_1, presence: true
    def name
        "#{first_name} #{last_name}".strip 
    end
    def full_address
        "#{address_line_1}, #{city}, #{state}, #{country}, #{pindcode}".strip
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only: [:edit, :update, :show, :destroy ]
    def index
        @employees = Employee.all
    end
    
    def new
        @employee = Employee.new
    end
    def create
        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to employees_path, notice: 'Employee has been created successfully'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @employee.update(employee_params)
            redirect_to employees_path, notice: 'Employee has been updated successfully' 
        else
            render :edit
        end
    end

    def show 
    end

    def destroy
        if @employee.destroy
            redirect_to employees_path, notice: 'Employee has been deleted successfully'
        end 
    end

    private
    def employee_params
        params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :address_line_1, :address_line_2, :city, :country, :state, :pindcode)
    end

    def set_employee
        @employee = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound => error
        redirect_to employees_path, notice: error
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @title_text = 'Hello World!'
        @subtitle_text = 'I am learning rails'
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_form.html.erb
 <%= form_with model: employee do |form| %>
    <div class="row">

   
    
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label :first_name, class: 'mb-2' %>
    <%= form.text_field :first_name, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label :middle_name, class: 'mb-2' %>
    <%= form.text_field :middle_name, class: 'form-control form-control-lg rounded-0'%>
    </div>
    </div>

    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label :last_name, class: 'mb-2' %>
    <%= form.text_field :last_name, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:last_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>
    </div>

    <div class="row">
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label :personal_email, class: 'mb-2' %>
    <%= form.email_field :personal_email, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:personal_email).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>
    </div>

    <div class="row">
    <div class="col-lg-6">
    <div class="form-group">
    <%= form.label :address_line_1, class: 'mb-2' %>
    <%= form.text_field :address_line_1, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>

    <div class="col-lg-6">
    <div class="form-group">
    <%= form.label :address_line_2, class: 'mb-2' %>
    <%= form.text_field :address_line_2, class: 'form-control form-control-lg rounded-0'%>
    </div>
    </div>

    <div class="col-lg-3">
    <div class="form-group">
    <%= form.label :city, class: 'mb-2' %>
    <%= form.text_field :city, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:city).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>

    <div class="col-lg-3">
    <div class="form-group">
    <%= form.label :state, class: 'mb-2' %>
    <%= form.text_field :state, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:state).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>

    <div class="col-lg-3">
    <div class="form-group">
    <%= form.label :country, class: 'mb-2' %>
    <%= form.text_field :country, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:country).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>

    <div class="col-lg-3">
    <div class="form-group">
    <%= form.label :pincode, class: 'mb-2' %>
    <%= form.text_field :pindcode, class: 'form-control form-control-lg rounded-0'%>
    <% @employee.errors.full_messages_for(:pindcode).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="col-lg-12 mt-4">
     <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
     <%= link_to "Back to Employees", employees_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
     </div>
    </div>
    <% end %>

app/views/employees/edit.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-5 mb-5">
<div class="card-body">
<h2 class="text-center">Edit Employee Information</h2>
</div>
</div>
<%= render 'form', employee: @employee %>
</div>


app/views/employees/index.html.erb
<div class="col-lg-12">
<%= flash[:notice] %>
<div class="card rounded-0 mt-5 mb-5">
<div class="card-body">
<h2 class="text-center">Listing Employees</h2>
</div>
</div>
<%= link_to "Create New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>
<table class="table table-bordered">
<thead>
<tr>
<th>Name</th>
<th>Personal Email</th>
<th>Address</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<% @employees.each do |employee|%>
    <tr>
    <td><%= employee.name %> </td>
    <td><%= employee.personal_email %></td>
    <td><%= employee.full_address %></td>
    <td>
    <div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Actions
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "Edit", edit_employee_path(employee), class: "dropdown-item" %></li>
    <li><%= link_to "View", employee_path(employee), class: "dropdown-item" %></li>
    <li> <%= link_to "Delete", employee_path(employee), class: "dropdown-item", method: :delete, data: { confirm: 'Are you sure to delete this employee'} %></li>
  </ul>
</div>
   
    </td>
    </tr>
    <% end %>
</tbody>
</table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-5 mb-5">
<div class="card-body">
<h2 class="text-center">Create New Employee</h2>
</div>
</div>
<%= render 'form', employee: @employee %>
</div>


app/views/employees/show.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-5 mb-5">
<div class="card-body">
<h2 class="text-center">Employee Details</h2>
<div class="row mt-5">
<div class="col-lg-6">
<h3 class="mb-3">Personal Information</h3>
<p class="lead"><strong>First Name:</strong><%= @employee.first_name %></p>
<p class="lead"><strong>Middle Name:</strong><%= @employee.middle_name.present? ? @employee.middle_name : '--NA--' %></p>
<p class="lead"><strong>Last Name:</strong><%= @employee.last_name %></p>
<p class="lead"><strong>Personal Email:</strong><%= @employee.personal_email %></p>
</div>
<div class="col-lg-6">
<h3 class="mb-3">Address Information</h3>
<p class="lead"><strong>Address Line 1:</strong><%= @employee.address_line_1 %></p>
<p class="lead"><strong>Address Line 2:</strong><%= @employee.address_line_2.present? ? @employee.address_line_2 : '--NA--' %></p>
<p class="lead"><strong>City:</strong><%= @employee.city %></p>
<p class="lead"><strong>State:</strong><%= @employee.state %></p>
<p class="lead"><strong>Country:</strong><%= @employee.country %></p>
<p class="lead"><strong>pincode:</strong><%= @employee.pindcode %></p>
</div>
</div>

<%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0' %>
<%= link_to 'Edit Employee', edit_employee_path(@employee), class: 'btn btn-primary btn-lg rounded-0' %>
</div>
</div>
</div>


app/views/home/index.html.erb
<h1><%= @title_text %></h1>
<p1><%= @subtitle_text %></p>

<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My HR" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
<h1 class="text-center mt-5 mb-4">About My-HR</h1>
<%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
<h1 class="text-center mt-5 mb-4">Contact Us</h1>
<%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
<h1 class="text-center mt-5 mb-4">Privacy Policy</h1>
<%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/pages/terms_and_conditions.html.erb
<div class="col-lg-10 mx-auto">
<h1 class="text-center mt-5 mb-4">Terms and Conditions</h1>
<%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/shared/_dummy_content.html.erb
<p class="lead">Our HRMS software provides a comprehensive solution for managing human resources efficiently and effectively. With features including employee information management, payroll automation, recruitment, time and attendance tracking, and performance evaluation, our system centralizes and streamlines HR processes into a single, user-friendly platform. It enhances accuracy, improves compliance, and boosts employee satisfaction through self-service portals and data-driven insights. By integrating seamlessly with other business systems, our HRMS adapts to your organization's growing needs, offering scalability and ease of use to optimize HR operations and drive strategic decision-making.</p>

<p class="lead">Our HRMS software provides a comprehensive solution for managing human resources efficiently and effectively. With features including employee information management, payroll automation, recruitment, time and attendance tracking, and performance evaluation, our system centralizes and streamlines HR processes into a single, user-friendly platform. It enhances accuracy, improves compliance, and boosts employee satisfaction through self-service portals and data-driven insights. By integrating seamlessly with other business systems, our HRMS adapts to your organization's growing needs, offering scalability and ease of use to optimize HR operations and drive strategic decision-making.</p>

<p class="lead">Our HRMS software provides a comprehensive solution for managing human resources efficiently and effectively. With features including employee information management, payroll automation, recruitment, time and attendance tracking, and performance evaluation, our system centralizes and streamlines HR processes into a single, user-friendly platform. It enhances accuracy, improves compliance, and boosts employee satisfaction through self-service portals and data-driven insights. By integrating seamlessly with other business systems, our HRMS adapts to your organization's growing needs, offering scalability and ease of use to optimize HR operations and drive strategic decision-making.</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
  <%= link_to 'My-HR', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<h1>My-HR</h1>
<%= link_to 'About us', about_path, target: '_blank', style: 'color: orange;' %>
<%= link_to 'Contact us', contact_path, target: '_blank', style: 'color: orange;' %>
<%= link_to 'Privacy policy', privacy_policy_path, target: '_blank', style: 'color: orange;' %>
<%= link_to 'Terms and conditions', terms_and_conditions_path, target: '_blank', style: 'color: orange;' %>